# docker-compose.yml
version: '3.8'

services:
  medical-coding-api:
    build: 
      context: ./api-gateway
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=medical_coding
      - DB_USER=postgres
      - DB_PASSWORD=postgres
<<<<<<< HEAD
      - OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Replace with your actual OpenAI API key
=======
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Ensure this is set in your environment
      - FHIR_SERVER_URL=http://hapi-fhir:8080/fhir
>>>>>>> 4417c00 (Updated Codebase)
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: medical_coding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

<<<<<<< HEAD
=======

>>>>>>> 4417c00 (Updated Codebase)
volumes:
  postgres_data: